// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/nativeshadr.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_as_is
Rcpp::IntegerVector test_as_is(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_test_as_is(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(test_as_is(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// test_gradient
Rcpp::IntegerVector test_gradient(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_test_gradient(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(test_gradient(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_sandy
Rcpp::IntegerVector shdr_sandy(Rcpp::IntegerMatrix nr, float lacunarity, float gain, float intensity, float octaves, float time);
RcppExport SEXP _nativeshadr_shdr_sandy(SEXP nrSEXP, SEXP lacunaritySEXP, SEXP gainSEXP, SEXP intensitySEXP, SEXP octavesSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< float >::type lacunarity(lacunaritySEXP);
    Rcpp::traits::input_parameter< float >::type gain(gainSEXP);
    Rcpp::traits::input_parameter< float >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< float >::type octaves(octavesSEXP);
    Rcpp::traits::input_parameter< float >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_sandy(nr, lacunarity, gain, intensity, octaves, time));
    return rcpp_result_gen;
END_RCPP
}
// shdr_asciifilter
Rcpp::IntegerVector shdr_asciifilter(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_asciifilter(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_asciifilter(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_deform
Rcpp::IntegerVector shdr_deform(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_deform(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_deform(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_godray
Rcpp::IntegerVector shdr_godray(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_godray(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_godray(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_retrofilter
Rcpp::IntegerVector shdr_retrofilter(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_retrofilter(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_retrofilter(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_rgb_split
Rcpp::IntegerVector shdr_rgb_split(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_rgb_split(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_rgb_split(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_ripple
Rcpp::IntegerVector shdr_ripple(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_ripple(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_ripple(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_shockwave
Rcpp::IntegerVector shdr_shockwave(Rcpp::IntegerMatrix nr, Rcpp::List uni);
RcppExport SEXP _nativeshadr_shdr_shockwave(SEXP nrSEXP, SEXP uniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_shockwave(nr, uni));
    return rcpp_result_gen;
END_RCPP
}
// shdr_twist
Rcpp::IntegerVector shdr_twist(Rcpp::IntegerMatrix nr, Rcpp::List uni, double padding);
RcppExport SEXP _nativeshadr_shdr_twist(SEXP nrSEXP, SEXP uniSEXP, SEXP paddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uni(uniSEXP);
    Rcpp::traits::input_parameter< double >::type padding(paddingSEXP);
    rcpp_result_gen = Rcpp::wrap(shdr_twist(nr, uni, padding));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nativeshadr_test_as_is", (DL_FUNC) &_nativeshadr_test_as_is, 2},
    {"_nativeshadr_test_gradient", (DL_FUNC) &_nativeshadr_test_gradient, 2},
    {"_nativeshadr_shdr_sandy", (DL_FUNC) &_nativeshadr_shdr_sandy, 6},
    {"_nativeshadr_shdr_asciifilter", (DL_FUNC) &_nativeshadr_shdr_asciifilter, 2},
    {"_nativeshadr_shdr_deform", (DL_FUNC) &_nativeshadr_shdr_deform, 2},
    {"_nativeshadr_shdr_godray", (DL_FUNC) &_nativeshadr_shdr_godray, 2},
    {"_nativeshadr_shdr_retrofilter", (DL_FUNC) &_nativeshadr_shdr_retrofilter, 2},
    {"_nativeshadr_shdr_rgb_split", (DL_FUNC) &_nativeshadr_shdr_rgb_split, 2},
    {"_nativeshadr_shdr_ripple", (DL_FUNC) &_nativeshadr_shdr_ripple, 2},
    {"_nativeshadr_shdr_shockwave", (DL_FUNC) &_nativeshadr_shdr_shockwave, 2},
    {"_nativeshadr_shdr_twist", (DL_FUNC) &_nativeshadr_shdr_twist, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_nativeshadr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
