// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/nativeshadr.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_as_is
Rcpp::IntegerVector test_as_is(Rcpp::IntegerMatrix nr, Rcpp::List uniforms);
RcppExport SEXP _nativeshadr_test_as_is(SEXP nrSEXP, SEXP uniformsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uniforms(uniformsSEXP);
    rcpp_result_gen = Rcpp::wrap(test_as_is(nr, uniforms));
    return rcpp_result_gen;
END_RCPP
}
// test
Rcpp::IntegerVector test(Rcpp::IntegerMatrix nr, Rcpp::List uniforms);
RcppExport SEXP _nativeshadr_test(SEXP nrSEXP, SEXP uniformsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type uniforms(uniformsSEXP);
    rcpp_result_gen = Rcpp::wrap(test(nr, uniforms));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nativeshadr_test_as_is", (DL_FUNC) &_nativeshadr_test_as_is, 2},
    {"_nativeshadr_test", (DL_FUNC) &_nativeshadr_test, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nativeshadr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
