# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_as_is <- function(nr, uni) {
    .Call(`_nativeshadr_test_as_is`, nr, uni)
}

test_gradient <- function(nr, uni) {
    .Call(`_nativeshadr_test_gradient`, nr, uni)
}

